### ISSUE TITLE
Return empty file during GET(Rails3.0.5, Passenger 3.0.6)

### ISSUE THREAD

**Issue by bioform** [chrisroberts/dav4rack#13]
I installed dav4rack to my rails project.
routes.rb:

mount DAV4Rack::Handler.new(:root => File.join(Rails.root, 'uploads'), :root_uri_path => "/box/webdav", :resource_class => ::DAV4Rack::FileResource), :at => 'webdav'

Project installed under Phusion Passenger 3.0.6 under subfolder:
    RackBaseURI /box
    <Directory /var/www/box>
        PassengerResolveSymlinksInDocumentRoot on
        AllowOverride all
        Options -MultiViews
    </Directory>

I upload files via Rails controller and then try to download them via WebDav.
I always get empty file.
Sometimes(I couldn't catch crash point) I can properly get file which was uploaded via WebDav.
I checked difference between these files(which was uploaded via rails controller and WebDav) - they looks the same.

Rack: rack (1.2.2, 1.2.1, 1.0.1)
dav4rack: dav4rack (0.2.3)

It looks like passenger incorrectly streaming Rack::File
Because all works properly under Webrick

**Comment by chrisroberts** [comment]
Installed Passenger 3.0.6 and tested upload/download with no problems. This was using a rails 2 app, which may be the problem. Can you make a gist of your apache config file and the applicable parts your routes.rb file. Hopefully this will help me get a configuration that will properly mimic your setup and allow the issue to be reproduced.

**Comment by bioform** [comment]
I found that this issue is reproduced if you install application not just to subfolder.
gist: https://gist.github.com/905363
I've just created test project to demonstrate effect.
File to test:
http://test1.3akupki.ru/webdav/low/twitter.png

Notice: I upload files via rails controller(see controller file name in the gist), not via webdav

**Comment by chrisroberts** [comment]
I'm still trying to chase this down. It looks to be something within rails 3, but I haven't been able to isolate it yet.

**Comment by chrisroberts** [comment]
Was never able to reproduce locally. If this is still an issue please reopen this ticket.
