### ISSUE TITLE
DAV4Rack::Handler should lock a resource

### ISSUE THREAD

**Issue by clyfe** [chrisroberts/dav4rack#14]
Running the specs on ubuntu:

```
.....................F

Failures:

  1) DAV4Rack::Handler should lock a resource
     Failure/Error: @response = request.request(method, uri, options)
     NoMethodError:
       undefined method `to_i' for :infinity:Symbol
     # ./lib/dav4rack/resource.rb:237:in `lock'
     # ./lib/dav4rack/controller.rb:186:in `lock'
     # ./lib/dav4rack/handler.rb:29:in `call'
     # ./spec/handler_spec.rb:29:in `request'
     # ./spec/handler_spec.rb:34:in `block (3 levels) in <top (required)>'
     # ./spec/handler_spec.rb:291:in `block (2 levels) in <top (required)>'

Finished in 0.21852 seconds
22 examples, 1 failure
```

The issue is that in controller.rb:314 the depth is set to `:infinity` and later in resource.rb:237 it tries to convert it `to_i`.
The thing is the depth option is already converted to integer in controller.rb#depth:312 (that is unless it's the `:infinity` symbol).

Removing the `#to_i` conversion in resource.rb:237 passes the specs but i'm not sure if it's the right way to go.

**Comment by chrisroberts** [comment]
Fixed with teefax's patch and available in v0.2.4
