### ISSUE TITLE
multi-status (207) for PUT requests

### ISSUE THREAD

**Issue by buffym** [chrisroberts/dav4rack#17]
First, thanks for dav4rack, it is certainly making my life easier. 

I'm working on providing a dav interface for a rails application, and am running litmus (http://www.webdav.org/neon/litmus/) for testing against dav4rack with my custom resource. Digging into the source, I see that controller.rb is always returning a multi-status as a response to valid put requests. This triggers a warning in litmus, saying the correct response should be 201 (Created). Also, I believe the WebDAV spec makes mention that a 201 status should not be included in a multi-status response because it is the default success code. I'm very new to WebDAV, so I wasn't sure if your implementation is because there is a client implementation that is expecting a multi-status response even though that isn't what the spec calls for? If not, I am working on a patch, which will return 201 for successful put requests and will issue a pull request when I'm finished. Thanks.

**Comment by chrisroberts** [comment]
The deviation was indeed related to a client specific implementation that other test clients seemed not to mind. I have no reservations at all about merging this in. I will be doing some work on a minor version bump (that drops rails 2 support) this weekend to finally get clyfe's callbacks in and at that point I'll merge your changes into that plus the tiny version bump for any rails 2 folks.

**Comment by buffym** [comment]
Bummer, I'm still on rails 2.3. Will you create a rails 2 branch? I've also made some other changes I'd like to submit back to you, improving propfind namespace support, etc. Thanks.

**Comment by chrisroberts** [comment]
Rails 2 support will continue on the 0.2.x branch. The new callbacks make use of the latest ActiveModel which makes it incompatible with Rails 2. I've played around with trying to provide a proper replacement in a Rails 2 environment but it introduces API incompatibilities which are not easily resolved.

So versions >= 0.3.0 will be for usage outside of Rails, or with Rails >= 3 and 0.2.x versions will be maintained for the Rails 2 folks. I'll keep backporting any internal updates it just means if any API changes are introduced in edge versions those changes will not be available in a Rails 2 environment.

**Comment by chrisroberts** [comment]
Merged and available as of 0.2.5 release.
