### ISSUE TITLE
Setup message broken by default

### ISSUE THREAD

**Issue by jbangert** [chrisroberts/dav4rack#19]
In the current version, if one creates a custom resource class, resource#initializer will rename the "setup" method of the custom resource class unless it is added to skip_alias, so only the first request will succeed, thereafter "NoMethodErrors" without a caller will appear which are a PITA to debug. Default behavior should have the setup method already in @skip_alias.

Just add :setup to @skip_alias in resource.rb, line 52.

**Comment by chrisroberts** [comment]
Resolved in 0.2.5 release.

Thank you for the bug report and my apologies for the trouble tracking the issue down. Clyfe's ActiveModel based callbacks in the 0.3.0 release should help in removing a lot of this indirection.
