### ISSUE TITLE
Properly implement locking for non-existent resources

### ISSUE THREAD

**Issue by doxavore** [chrisroberts/dav4rack#21]
`DAV4Rack::Controller#lock` raises a NotFound response when the resource doesn't exist. This isn't correct behavior, per RFP4918 sections _7.3 Write Locks and Unmapped URLs_ and _9.10.4 Locking Unmapped URLs_: http://www.webdav.org/specs/rfc4918.html  Finder on Mac OS X will not allow you to create files and will revert to treating the server as read-only when it doesn't properly implement this spec form of locking.

I believe the best course of action may be to allow the `resource.lock(asked)` call, as the resource should decide if it should create itself as a blank file (generally correct per the spec) or do something else.

Is there any reason we can't start by removing the `raise NotFound unless resource.exist?` line, as `resource.exist?` has no knowledge that this is an attempt at locking?

**Comment by chrisroberts** [comment]
Existence check removed. Resolved as of 0.2.8
