### ISSUE TITLE
Returning anything but "Created" for resource put request results in nil-error

### ISSUE THREAD

**Issue by cweyer** [chrisroberts/dav4rack#23]
I have a custom resource that only allows certain content types to be uploaded. Everything works fine until the error handling kicks in. I wanted the Dav4Rack to return either Forbidden or UnspportedMediaType, but I will ran into the following error when returning anything else to the put request but "Created" or "NoContent".

My Code (TemplateResource#put):

``` ruby
def put(reuqest, response)
    tempfile = Tempfile.new(object_id)

    # Read the contents
    while part = request.body.read(8192)
      tempfile.write(part)
    end

    # Build an uploaded file as a normal rails request
    # would do to give Paperclip a way to access file
    # meta data
    @template.template = ActionDispatch::Http::UploadedFile.new({
      :filename => path.split('/').last,
      :tempfile => tempfile
    })

    if @template.save
      Created
    else
      UnsupportedMediaType
    end
  ensure
    tempfile.close
    tempfile.unlink        
  end
```

Backtrace: (Mac OS 10.7.1, Rails 3.1, dav4rack is straight from GIT)

[2011-09-24 17:36:36] INFO  WEBrick 1.3.1
[2011-09-24 17:36:36] INFO  ruby 1.8.7 (2010-01-10) [universal-darwin11.0]
[2011-09-24 17:36:36] INFO  WEBrick::HTTPServer#start: pid=3890 port=3000
[2011-09-24 17:36:46] ERROR NoMethodError: undefined method `bytesize' for nil:NilClass
    /Library/Ruby/Gems/1.8/gems/activesupport-3.1.0/lib/active_support/whiny_nil.rb:48:in`method_missing'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/utils.rb:256:in `bytesize'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/rack/content_length.rb:28:in`call'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/response.rb:86:in `each'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/response.rb:86:in`each'
    /Library/Ruby/Gems/1.8/gems/activerecord-3.1.0/lib/active_record/query_cache.rb:45:in `each'
    /Library/Ruby/Gems/1.8/gems/activerecord-3.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:458:in`each'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/body_proxy.rb:26:in `__send__'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/body_proxy.rb:26:in`method_missing'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/rack/content_length.rb:26:in `call'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/rack/log_tailer.rb:14:in`call'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/handler/webrick.rb:59:in `service'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:92:in`each'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:23:in`start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/handler/webrick.rb:13:in`run'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/server.rb:265:in `start'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands/server.rb:70:in`start'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands.rb:54
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands.rb:49:in `tap'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands.rb:49
    script/rails:6:in`require'
    script/rails:6

**Comment by chrisroberts** [comment]
The handler is making a bad assumption when setting the body content. Until I push a fix up, an easy solution would be to raise the status instead of returning it.

**Comment by chrisroberts** [comment]
I believe this has been resolved. If not, please reopen this ticket
