### ISSUE TITLE
URIs with special chars are not escaped before given to the web server

### ISSUE THREAD

**Issue by cweyer** [chrisroberts/dav4rack#24]
I first found this problem while working with custom resources. In order to make sure it had nothing to do with my code, I made my Rails app directory a DAV4Rack::FileResource but the problem persists, if you try to do anything with URIs that contain spaces or other characters that would require escape.

I tried doing the escaping on my own (in Resource#name i.e.) but ran into several other errors that made me believe the way it is intended to be, is not to handle the escape myself, but for some deeper layer to do it, as is done for unescaping, too?

Backtrace (Mac OS 10.7.1, Ruby 1.8.7, Rails 3.1, DAV4Rack from git, Rack 1.3.3):

Started PUT "/public/unbenannte%20Datei" for 127.0.0.1 at Mon Sep 26 21:38:13 +0200 2011
[2011-09-26 21:38:13] ERROR URI::InvalidURIError: bad URI(is not URI?): http://files.shipyard.cornerstoreapp.local:3000/public/unbenannte Datei
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/uri/generic.rb:732:in `merge'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/httpresponse.rb:164:in`setup_header'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/httpresponse.rb:102:in `send_response'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/httpserver.rb:79:in`run'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:162:in`start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:95:in`start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:92:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:92:in`start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:23:in `start'
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/webrick/server.rb:82:in`start'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/handler/webrick.rb:13:in `run'
    /Library/Ruby/Gems/1.8/gems/rack-1.3.3/lib/rack/server.rb:265:in`start'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands/server.rb:70:in `start'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands.rb:54
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands.rb:49:in`tap'
    /Library/Ruby/Gems/1.8/gems/railties-3.1.0/lib/rails/commands.rb:49
    script/rails:6:in `require'
    script/rails:6

**Comment by chrisroberts** [comment]
My suspicion with the stacktrace provided was that this is an issue with webrick rather than dav4rack, and after some testing locally this does seem to be the case. Please try loading your application up using something other than webrick (like unicorn or thin) and see if your issue persist. I believe that this is webrick specific but I'll keep this open until you confirm resolution.

**Comment by doxavore** [comment]
I've not had a problem with spaces, but if I have any international characters (such as `naïvefile.jpg`) I can't seem to get any WebDAV client to display them. Macs and iPads just skip them, and the Windows WebClient built into Windows Explorer shows a 0-byte file with a name of a full URL.

Has anyone else experienced this?

**Comment by cweyer** [comment]
My problems vanished (as chris suggested) when trying another webserver. I also have a strange upload problem with the finder that leaves empty files on the webdav sometimes which does only happen with webrick. Using apache solved all the problems I had.

**Comment by chrisroberts** [comment]
Going to close this up now. If you encounter any other problems like this, please reopen this ticket or start a new one.
