### ISSUE TITLE
windows xp 

### ISSUE THREAD

**Issue by schmurfy** [chrisroberts/dav4rack#25]
Hi,
did anyone managed to make it work with windows xp ?
I did many tests and cannot find a configuration which is working with it :/

**Comment by xykox** [comment]
It's an advice : forget it, and try to use another client :
http://barracudaserver.com/products/BarracudaDrive/tutorials/mapping_windows_drive.lsp

I try with windows 7 and it works.

**Comment by schmurfy** [comment]
Yeah I gave up on windows native client, I managed to make it works more or less but some things are not working and cannot work: you can copy a file on your local disk, edit it and copy it back on the webdav share but you cannot edit it on the webdav share and cannot save there.

The results from my tests is that webdav is buggy in all windows version but each one has its own set of bugs, better use a real webdav client than their ****.
