### ISSUE TITLE
Rails 3.x app with Devise and WebDav

### ISSUE THREAD

**Issue by januszm** [chrisroberts/dav4rack#27]
I would like to enable WebDav for Rails 3.1 application, where I use Devise for authentication and CanCan for authorization.

So far I turned on WebDav and works fine. Is it possible to use Devise logins/users with dav4rack ? An then, enable/restrict access to certain files/directories on WebDav for users? Maybe there is already a howto or wiki page about that? Any help will be appreciated.

PS. is this the right way of solving this kind of problem? maybe i should switch back to apache mod_dav and synchronise apache's dav users with devise users?

**Comment by chrisroberts** [comment]
The file resource by default just does very basic username/password authentication. An easy way to add support for devise would be to override the authenticate method to do authentication based on your requirements. The authenticate method takes a username and password to authenticate the user before proceeding. So, overriding after requiring in the file resource like this might suffice:

``` ruby
class DAV4Rack::FileResource
  private
  def authenticate(username, password)
    @authed ||= User.find_by_username(username).try(:valid_password?, password)
  end
end
```

Disclaimer that none of that has been tested and I have never used devise before, but that should get you on the right track. Please let me know if it works out for you.

**Comment by januszm** [comment]
OK Thanks!

I put this (slightly modified - there is 'find_by_email' because devise uses email as login)

``` ruby
class DAV4Rack::FileResource
  private
  def authenticate(username, password)
    @authed ||= User.find_by_email(username).try(:valid_password?, password)
  end
end
```

into 

```
config/initializers/webdav.rb 
```

(just after 'require dav4rack/file_resource' line, like in rails 3 dav4rack example)

Works fine but remember to activate http auth in devise initializer

```
config/initializers/devise.rb
```

uncomment

``` ruby
  config.http_authenticatable = true
```

On MacOS X there is a problem with upload. I can't upload files with dav4rack, files are shrinked to 512 bytes or something like this, and have content "2000".
At the end of PUT process i get  '... some data in "filename_here"  can't be read or written. (Error code -36)'.  This should be related to "dot underscore" problem.

From linux client, using davfs there is no problem.

**Comment by januszm** [comment]
Now I have next question, how to add some properties to the files/directories, so that files BELONG to users, like in normal *nix/Linux filesystem.
If there is an option to put some extra properties, like USER_ID to each file, that would be perfect. I guess using  PROPPATCH to set up rails_user_id on a file could be a solution?

**Comment by chrisroberts** [comment]
With regards to the mac based uploads, what httpd frontend are you using? If it's nginx then that will be the problem. The os x client will do multi-part uploads and nginx does not support it.

As far as adding more logic into the resource (like assigning ownership to files), it will likely be outside the scope of the file resource that comes with the library. However, this library was built specifically for making the resource used for managing file interactions to be easily changed. For example, I use an S3 based resource to simulate an actual file system and it allows for user ownership, permissions and a host of other things that work in tandem with a rails application.

If you are needing more control over how access is provided to your files and the like, you may want to create your own resource to use. Since it sounds like you will just need to add some extra functionality to what is already available, you could easily just start with the file resource from this library and either override the methods required to add in proper ownerships, or create a brand new resource with the file resource as a template.

**Comment by januszm** [comment]
I'm using thin only, so simple situation, just

```
thin start -p 5000
```

maybe thin can't handle multi-part too.

I will work on modifications to FileResource then.

**Comment by bryanrite** [comment]
Hey @januszm, not sure if you're finished your implementation or not, but I did something very similar.  

I wrote a tutorial about it: https://github.com/chrisroberts/dav4rack/wiki/Advanced-Rails-3-Tutorial---Custom-Resource,-Devise,-and-User-Specific-Routing

and there is a sample app available as well: https://github.com/bryanrite/dav4rack-example-devise-subdirectories

All using Devise for authentication and segregated files for each user.  Hope that helps.

**Comment by januszm** [comment]
Hi, this is great, thanks for the information. I had to stop the development of this part of my app and for now switched to ready-made Groupware solution, but looks like I have to revise my plans.

**Comment by marknadig** [comment]
@chrisroberts re "For example, I use an S3 based resource to simulate an actual file system and it allows for user ownership, permissions and a host of other things that work in tandem with a rails application." - any chance that source will be opened up?

**Comment by chrisroberts** [comment]
Hi! Unfortunately no, it's not something that I have ownership of to open up. It was part of a Rails application I worked on in the past. If you want to make a resource to do something similar it should be pretty straight forward. The current file resource should give you a good idea of what you need to provide, and fog would work great for s3 interactions. Depending on your usecase and the quantity of assets being stored, you could handling directory listings either on demand (direct s3 requests for keys with specific prefixes) and then filter the applicable values (current directory) or you could go more heavy handed and use something like acts_as_sane_tree to track assets and parent relations which would provide faster on the fly tree building and depth querying.

Anyway, if you start hacking on a resource and get stuck, feel free to ping and I'll offer suggestions if I can.

**Comment by marknadig** [comment]
Thanks for the reply. Yeah, the file resource and dav4rack_ext's cardav should give enough examples to hack away at. In  my case, it's actually going to be webdav -> paperclip (which may be local or s3 depending on environment).

**Comment by rogsmith** [comment]
@marknadig did you ever end up implementing that solution? I am looking to do the same.

**Comment by marknadig** [comment]
oh man, I'm 5 years off that project and don't have access to that source :/

**Comment by rogsmith** [comment]
Thx @marknadig. No worries. Were you able to get it going relatively easily though?

**Comment by marknadig** [comment]
@rogsmith I honestly don't remember :/   Sorry. Good luck. 
https://xkcd.com/979/
