### ISSUE TITLE
Username Subdirectories

### ISSUE THREAD

**Issue by bryanrite** [chrisroberts/dav4rack#29]
In a continuation of this issue: 

https://github.com/chrisroberts/dav4rack/issues/27

I'm trying to setup exposing subdirectories based on the user's authenticated username... ie:
- root_dir
  - username1
  - username2

ie. expose /root_dir/username1 as / if the user logins with username1, i'm just having an issue as to where to put the logic?

I'd love to put together an advanced example for the Wiki of setting up Dav4Rack w/ Devise and subdirectories once I get it all working.

Thanks in advance!

**Comment by chrisroberts** [comment]
Hi. This should be pretty easy to accomplish. Assuming you have a custom resource based on the FileResource:

``` ruby
class MyResource < FileResource
  protected
  def file_path
    File.join(root, options[:username], path)
  end
end
```

Or, if you are using the FileResource directly, you can modify its behavior at runtime:

``` ruby
FileResource.class_eval do
  protected
  def file_path
    File.join(root, options[:username], path)
  end
end
```

The FileResource uses the `file_path` method when dealing with local paths, so overriding it should give you the desired behavior. If you are doing something different and these approaches don't apply, please provide your Resource and we can go from there.

**Comment by bryanrite** [comment]
That is working fantastically, thanks Chris, missed the file_path in the docs.

Once I get this all ironed out, I'll submit something to the wiki.

**Comment by chrisroberts** [comment]
Fantastic, looking forward to it. I'm going to close this issue up but please feel free to reopen it if you run into anything else.

**Comment by bryanrite** [comment]
Hey Chris, is there a trick with FileResource instance variables?

``` ruby
class TestResource < DAV4Rack::FileResource

  def auth_id
    @auth_id
  end

  def auth_id=(value)
    @auth_id = value
  end

  def file_path
    File.join(root, auth_id, path)
  end

  private
    def authenticate(username, password)
      case username
      when 'user1'
        @authed = true
        self.auth_id = '1'
      when 'user2'
        @authed = true
        self.auth_id = '2'
      else
        @authed = false
      end
      @authed 
    end
end
```

`auth_id` is always nil but authentication works (ie. valid if user1/user2, invalid if anything else). I'm missing something... thanks again for your help.

**Comment by bryanrite** [comment]
I've done a majority of a new wiki page documenting setting up rails, devise, and username subdirectories, just stuck on this last piece of storing an instance variable, not sure what i'm doing wrong as the parent classes store instance variables fine.

**Comment by chrisroberts** [comment]
I wrapped up your test resource to test and I'm getting expected results. Here's what I used:

``` ruby
# davtest.rb
require 'rubygems'
require 'ostruct'
require 'dav4rack'
require 'dav4rack/file_resource'

class TestResource < DAV4Rack::FileResource

  def auth_id
    @auth_id
  end

  def auth_id=(value)
    @auth_id = value
  end

  def file_path
    File.join(root, auth_id, path)
  end

  private
    def authenticate(username, password)
      case username
      when 'user1'
        @authed = true
        self.auth_id = '1'
      when 'user2'
        @authed = true
        self.auth_id = '2'
      else
        @authed = false
      end
      @authed 
    end
end

res = TestResource.new('somefile.txt', 'somefile.txt', OpenStruct.new, OpenStruct.new, :root => '/my/private/root')
puts 'User: user3'
res.send(:authenticate, 'user3', 'blah')
begin
  puts "File path: #{res.file_path}"
rescue => e
  puts "NO GO: #{e}"
end

puts '*' * 10

res.send(:authenticate, 'user1', 'blah')
puts 'User: user1'
puts "File path: #{res.file_path}"
```

with the results being:

```
○ → ruby davtest.rb                                                                                                                       
User: user3
NO GO: can't convert nil into String
**********
User: user1
File path: /my/private/root/1/somefile.txt
```

Could you do a quick sanity check and make sure you get the same results. Also, logging the username and password #authenticate is getting might help to provide some clues as to what's going on.

**Comment by bryanrite** [comment]
Yes, your test works here too.  Hrm.  It might be an issue only when listing the directory.

**Comment by chrisroberts** [comment]
Ah, it's an issue of propagating the user to the children. Try throwing this in your test resource:

``` ruby
class TestResource < FileResource
  def children
    super.map{|kid| kid.auth_id = self.auth_id; kid}
  end
end
```

Let me know if that gets it working for you.

**Comment by bryanrite** [comment]
Beauty, you beat me to it :)

Thanks, I'll update my wiki entry and add a new one for interfacing with S3.

**Comment by chrisroberts** [comment]
Just a quick note on this. Mapping the children is functionally correct but adds an extra iteration over the collection that is not required. While it won't make a significant difference when building child nodes for a small directory, it will affect performance on large directories. The Resource has a #user that can be set and is auto-propagated to child nodes. So, if we go off your devise example, we could modify it to look something like this:

``` ruby
class TestResource < FileResource
  protected
  def file_path
    File.join(root, user.try(:username).to_s, path)
  end
  def authenticate
    self.user ||= User.find_by_username(username).try(:valid_password?, password)
  end
end
```

This removes the extra iteration and makes the required code a bit more compact.

**Comment by bryanrite** [comment]
Thanks Chris, I noticed that would be an issue and was going to look at optimizing it today.  Your help is again timely and appreciated.

**Comment by bryanrite** [comment]
This may be problematic because user variable is defaulted to "127.0.0.1" on every request.  I guess there is no way to persist data across WebDAV requests to save from authenticating each time.  Basically self.user will have to be set every time:

``` ruby
def authenticate
   self.user = User.find_by_username(username).try(:valid_password?, password)
end
```

Otherwise user[:username] doesn't exist because user = "127.0.0.1" and you get a Type Mismatch Error.

**Comment by bryanrite** [comment]
I also think there is an issue with GET, as its not routing properly.  Currently troubleshooting.

**Comment by bryanrite** [comment]
Yah, looks like `get` does not take into account an overridden file_path to serve files.  Trying to figure out how to fix.

**Comment by bryanrite** [comment]
FYI:

```
Started GET "/test/foo.txt" for 127.0.0.1 at 2012-01-27 13:29:31 -0800

ActionController::RoutingError (No route matches [GET] "/test/foo.txt"):


Rendered /Users/brite/.rvm/gems/ruby-1.9.2-p290/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (15.2ms)
```

When I'm trying to download a file from `/brite/test/foot.txt`

**Comment by chrisroberts** [comment]
With regards to having to authenticate every request, that is technically true since everything is stateless, however, you can use cookies to flag that a user has been authenticated. For example (and this is a very insecure example):

``` ruby
class MyResource < FileResource
  before do |resource, method_name|
    if(resource.request.cookies['dav_user'].present?)
      resource.user = User.find_by_username(resource.request.cookies['dav_user'])
    end
  end
  ...
  def authenticate
    if(self.user.is_a?(User))
      true
    else
      if(u = User.find_by_username(username).try(:valid_password?, password))
        self.user = u
        response.set_cookie('dav_user', u.username)
      end
    end
  end
end
```

Again, very insecure but just here for an example.

As for the GET error, it looks like the routing is failing. If you can paste in what your routes look like for the DAV stuff, I can throw together a dummy app this evening and see if I can replicate what you are experiencing.

**Comment by chrisroberts** [comment]
Ah, I missed your note about `get` not using the file_path. Instead of overriding the `file_path` method, try overriding the `root` method instead (since `file_path` uses that anyway):

``` ruby
  ...
  def root
    File.join(options[:root].to_s, user.username)
  end
  ...
```

**Comment by bryanrite** [comment]
Thats all it took Chris. :)

I was trying some wonky stuff with the request object and routing.  Thanks for the Rack lessons ;)
