### ISSUE TITLE
authentication and check_authentication in FileResource

### ISSUE THREAD

**Issue by clyfe** [chrisroberts/dav4rack#7]
Why does file resource provide both `authentication` and `check_authentication` callbacks, since they do the same thing? 

It seems enough to provide `authentication`.

`check_authentication` should be deleted, since it does the same thing.

**Comment by chrisroberts** [comment]
The reason they are both present is that the file resource was included mainly for an example of how to build a resource. Now that the wiki is up I'll work on getting things like that pulled out into the wiki and stripping the file resource down to only what is required.

**Comment by chrisroberts** [comment]
Callback authentication was removed from the file resource
