### ISSUE TITLE
Interceptor brakes Rails REST updates (and proposed solution)

### ISSUE THREAD

**Issue by clyfe** [chrisroberts/dav4rack#9]
Using the DAV4Rack::Interceptor with  Rails app, when updating a resource from the Rails app, the request is routed by the Interceptor to the webdav handler insted of routing it to the Rails app.

The problem is that the Interceptor, to compute where to forward the request, looks at the HTTP method and PUT is both core HTPP valid verb (used by Rails on updates) and Webdav verb.

As the Interceptor is only used to create the virtual mapping (from host root to dav mount point) I think the only HTTP methods it should check are OPTIONS and PROPFIND, or all dav verbs except PUT (not sure on these).

Sample code:

```
# the current situation in /dav4rack/interceptor.rb +14
if(@roots.detect{|x| path =~ /^#{Regexp.escape(x.downcase)}\/?/}.nil? && %w(OPTIONS PUT PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK).include?(method))

# proposed change in /dav4rack/interceptor.rb +14
if(@roots.detect{|x| path =~ /^#{Regexp.escape(x.downcase)}\/?/}.nil? && %w(OPTIONS PROPFIND).include?(method))
```

For my own needs to overcome this I made a cusom Interceptor

```
module Webdav
  class Interceptor < DAV4Rack::Interceptor
    def call(env)
      path = env['PATH_INFO'].downcase
      method = env['REQUEST_METHOD'].upcase
      app = nil
      if(@roots.detect{|x| path =~ /^#{Regexp.escape(x.downcase)}\/?/}.nil? && %w(OPTIONS PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK).include?(method))
        app = DAV4Rack::Handler.new(:resource_class => DAV4Rack::InterceptorResource, :mappings => @args[:mappings], :log_to => @args[:log_to])
      end
      app ? app.call(env) : @app.call(env)
    end
  end
end
```

**Comment by chrisroberts** [comment]
So the original reason for the interceptor was less to provide a nicety for doing a webdav connect (and simply providing a path on connection) but mainly for clients that expect to be able to access root or ancestors of the current path (which I ran into a lot on windows). This is the reason for a more encompassing inclusion of HTTP methods. I will run some tests tonight and perhaps allow a mechanism to turn off which methods are allowed to be intercepted on setup.

**Comment by chrisroberts** [comment]
PUT was removed from intercepted methods and there is a setting available now to ignore others if needed.
